excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://pandar3n.github.io
title: Leon Ho
tagline: A log of everyday life
description: I can't see what's on the paper!<br /><br />Junior Web Developer | Rookie IT Engineer
paginate: 5